cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', detail, name='detail'),
    path('add/<int:product_id>', add, name='product_add'),
    path('remove/<int:product_id>', remove, name='product_remove'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls')),
    path('coupon/',include('coupon.urls')),
    path('', include('shop.urls')),
]

coupon/urls.py
from django.urls import path
from .views import add_coupon

app_name = 'coupon'

urlpatterns = [
    path('add/', add_coupon, name='add'),
]

shop/urls.py
from django.urls import path
from .views import *

app_name = "shop"

urlpatterns = [
    path('', product_in_category, name="product_all"),
    path('<category_slug>/', product_in_category, name="product_in_category"),
    path('<int:id>/<product_slug>/', product_detail, name="product_detail"),
]

cart/models.py
from django.db import models

# Create your models here.

coupon/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.

class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    use_from = models.DateTimeField()
    use_to = models.DateTimeField()

    amount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10000)])
    active = models.BooleanField()

    def __str__(self):
        return self.code

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length = 200, db_index = True)
    meta_description = models.TextField(blank=True) # For SEO (Search Engine Optimization)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name="products")
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, allow_unicode=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)

    price = models.DecimalField(max_digits=10, decimal_places=0)
    stock = models.PositiveIntegerField()

    available_display = models.BooleanField('Display', default=True)
    available_order = models.BooleanField('Order', default=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        index_together = [['id', 'slug']] # multi colum index

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class AddProductForm(forms.Form):
    quantity = forms.IntegerField(label="구매 개수", label_suffix=" = ", min_value=1)
    is_update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    # 유효성 체크
    def clean_quantity(self):
        data = self.cleaned_data['quantity']

        #Check lte zero
        if data <= 0:
            raise ValidationError(_("Invalid data : Quantity isn\'t minus"))

        return data

coupon/forms.py
from django import forms

class AddCouponForm(forms.Form):
    code = forms.CharField(label='쿠폰을 입력하세요.')

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import AddProductForm
from .cart import Cart
from coupon.forms import AddCouponForm

@require_POST
def add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = AddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], is_update=cd['is_update'])

    return redirect('cart:detail')


def remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()

    passon = {
        'cart': cart,
        'add_coupon': add_coupon
        }

    for product in cart:
        init_val = {
            'quantity' : product['quantity'],
            'is_update':True # 장바구니에서는 업데이트 True
            }
        product['quantity_form'] = AddProductForm(initial=init_val)

    return render(request, 'cart/detail.html', passon)

coupon/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.decorators.http import require_POST

from .models import Coupon
from .forms import AddCouponForm

@require_POST
def add_coupon(request):
    now = timezone.now()
    form = AddCouponForm(request.POST)

    if form.is_valid():
        code = form.cleaned_data['code']

        try:
            coupon = Coupon.objects.get(code__iexact=code, use_from__lte=now, use_to__gte=now, active=True)
            request.session['coupon_id'] = coupon.id
            
        except Coupon.DoesNotExist:
            request.session['coupon_id'] = None

    return redirect('cart:detail')

def detail(request):
    cart = Cart(request)
    add_coupon = AddCouponForm()

    for item in cart:
        init_item = {
        'quantity':item['quantity'],
        'is_update':True
        }

        item['quantity_form'] = AddProductForm(initial=init_item)

    passon = {
        'cart': cart,
        'add_coupon': add_coupon
    }
    return render(request, 'cart/detail.html', passon)

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, Product
from cart.forms import AddProductForm


def product_in_category(request, category_slug=None):
    current_category = None

    categories = Category.objects.all()
    products = Product.objects.filter(available_display=True)

    if category_slug:
        current_category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=current_category)

    passon = {
        'current_category': current_category,
        'categories': categories,
        'products': products
    }
    return render(request, 'shop/list.html', passon)


def product_detail(request, id, product_slug=None):
    product = get_object_or_404(Product, id=id, slug=product_slug)

    # 제품 설명에서는 Update False
    add_to_cart = AddProductForm(initial={'quantity': 1})

    passon = {
        'product':product,
        'add_to_cart': add_to_cart
    }
    return render(request, 'shop/detail.html', passon)

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
장바구니
{% endblock %}

{% block content %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">사진 </th>
        <th scope="col">상품</th>
        <th scope="col">갯수</th>
        <th scope="col">삭제</th>
        <th scope="col">개당 가격</th>
        <th scope="col">합계</th>
      </tr>
    </thead>
    <tbody>
    {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <th scope="row">
          <a href="{{ product.get_absolute_url }}">
            <img src="{{ product.image_url|default_if_none:'#' }}" class="img-thumb-nail">
          </a>
        </th>
        <td>{{ product.name }}</td>
        <td>
          <form action="{% url  'cart:product_add' product.id %}">
            {{ item.quantity_form.quantity }}
            {{ item.quantity_form.is_update }}
            <input type="submit" class="btn btn-primary" value="Update">
          </form>
        </td>
        <td><a href="{% url 'cart:product_remove' product.id %}">삭제</a></td>
        <td class="num">{{ item.price }} 원</td>
        <td class="num">{{ item.total_price }} 원</td>
      </tr>
      {% endwith %}
    {% endfor %}
    <!-- 쿠폰 부분 시작 -->
    {% if cart.coupon %}
      <tr class="subtotal">
        <td>합계</td>
        <td colspan="4"></td>
        <td>{{ cart.get_product_total }} 원</td>
      </tr>
      <tr>
        <td>"{{ cart.coupon.code }}" 할인 쿠폰 ({{ cart.coupon.amount }}원)</td>
        <td colspan="4"></td>
        <td>- {{ cart.get_discount_total }} 원</td>
      </tr>
    {% endif %}

    <tr class="total">
      <td> 총합 </td>
      <td colspan="4"></td>
      <td class="num">{{ cart.get_total_price }} 원</td>
    </tr>
    </tbody>
  </table>
  <p> 쿠폰 사용 </p>
  <form action="{% url "coupon:add" %}" method="post">
    {{ add_coupon }}
    <input type="submit" value="추가">
    {% csrf_token %}
  </form>
  <p class="text-right"><a href="{% url 'shop:product_all'%}" class="btn btn-secondary">쇼핑 이어하기</a></p>

{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}

{% block title %}
제품 상세 정보
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-4">
        <img src="{{ product.image_url|default_if_none:'#' }}" alt="" width="100%">
      </div>
      <div class="col">
        <h1 class="display-6">{{ product.name }}</h1>
        <p><span class="badge badge-secondary">가격</span>{{ product.price }} 원</p>
        <form action="{% url 'cart:product_add' product.id %}" method="post">
          {{ add_to_cart }}
          {% csrf_token %}
          <input type="submit" class="btn btn-primary btn-sm" value="Add to Cart">
        </form>
        <h5><span class="badge badge-secondary">제품 설명</span> {{ product.description | linebreaks }}</h5>
      </div>
    </div>
  </div>
{% endblock %}

shop/templates/shop/list.html
{% extends 'base.html' %}

{% block title %}
Category Page
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-2">
      <div class="list-group">
        <a href="/" class="list-group-item {% if not current_category %} active {% endif %}">ALL</a>
        {% for cate in categories %}
          <a href="{{ cate.get_absolute_url }}" class="list-group-item {% if current_category.slug == cate.slug %} active {% endif %}">{{ cate.name }}</a>
        {% endfor %}
      </div>
    </div>

    <div class="col">
      <div class="alert alert-info" role="alert">
        {% if current_category %}
          {{ current_category.name }}
        {% else %}
          전체 상품 목록
        {% endif %}
      </div>

      <div class="row">
        {% for product in products %}
          <div class="col-4">
            <div class="card">
              <img src="{{ product.image_url|default_if_none:'#'}}" alt="Product Image" class="card-img-top">
              <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.price }} 원</p>
                <p class="card-text">{{ product.description}}
                  <a href="{{ product.get_absolute_url }}" class="btn btn-primary">자세히 보기</a>
                </p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <title>{% block title %} {% endblock %}</title>
  {% block script %}  {% endblock %}
  {% block style %} {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a href="/" class="navbar-brand">인터넷 쇼핑</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="flase" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav justify-content-end">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a href="{% url 'account_logout' %}" class="nav-link">Logout</a>
        {% else %}
        <a href="{% url 'account_login' %}" class="nav-link">Login</a>
        {% endif %}
      </li>
      <li class="nav-item active">
      장바구니
      <a href="{% url 'cart:detail' %}" class="nav-link btn btn-outline-success">
      {% if cart|length > 0 %}
        합계: {{ cart.get_total_price }} 원
      {% else %}
        : 비어있음
      {% endif %}
      </a>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  {% block content %} {% endblock %}
</div>
</body>
</html>